version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "29017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: EMO_Care_Center

volumes:
  mongo_data:
